name: GitHub 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight (UTC)
  workflow_dispatch:      # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          USERNAME: Dhinakaran311
          SETTINGS: >
            {
              "theme": "night_view", 
              "output": "./profile-3d-contrib"
            }

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: profile-3d-contrib
          commit_message: Update 3D contribution graph
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
